apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  selector:
    app: flask-proxy-server
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer
  externalIPs:
  - 34.94.244.167

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-proxy-server
spec:
  selector:
    matchLabels:
      app: flask-proxy-server
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-proxy-server
    spec:
      containers:
      - name: flask-proxy-server
        image: flask-proxy-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
